version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - JWT_SECRET=your_secret_key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
